### ISSUE TITLE
Problems with iperf3 on WAN lines with high latency

### ISSUE THREAD

**Issue by jonimessi** [perfsonar/bwctl#39]
I am using iperf3 (version 3.1.6 on FreeBSD) in conjunction with BWCTLD (version 1.5.4). On wan lines with high latency I get often errors in measruments via "bwctl -T iperf3 ... "

WARNING: Size of data read does not correspond to offered length
iperf3: error - unable to receive results: Resource temporarily unavailable

Does anyone know whats the reason for the Warning causing the iperf3 error?
Are there any parameters which can be switched to have a stable test on wan lines with high latency?

Thanks in advance!

**Comment by jonimessi** [comment]
It seems to be the problem that the bwctl scheduling window is a few seconds too short, so the test cannot finish completely. Where is the length of scheduling window set? Any idea how to make scheduling window longer (cause of high RTT?)

**Comment by mckaygerhard** [comment]
any news on this? Where is the length of scheduling window set? so we can patch by itselft

**Comment by mfeit-internet2** [comment]
@mckaygerhard  The last vestiges of support for BWCTL were [removed in 2019](https://www.perfsonar.net/releasenotes-2019-08-19-4-2.html) and we have ended maintenance.

A a `link-rtt` parameter was added to the pScheduler `throughput` test as part of https://github.com/perfsonar/pscheduler/issues/868 and the tool plugins for `iperf2` and `iperf3` can use it.

**Comment by mckaygerhard** [comment]
ok.. but you sound as a propaganda, i dont care that software i asking about the bwctl .. the line where we can change that..  i can cited that this software still works perfect @mfeit-internet2

**Comment by mfeit-internet2** [comment]
@mckaygerhard BWCTL has reached end of life.  The perfSONAR development team no longer maintains or supports it.

**Comment by mckaygerhard** [comment]
@mfeit-internet2  i asked about a near line or something.. not requested support.. lest make a examplet to ilustrate:

> mckaygerhard: @mfeit-internet2  in your previous job you always buy coffe?
> mfeit-internet2 : i dont support anymore my previous job

in fact your answer is propagandistic (because bwctl works for me), shabby, pretty (because you don't want to give it and you tell me to use something I don't want) and even rude because you avoid something simple to answer, and in case you don't know, why do you advertise thems?

the new version is too complicated, big and cumbersome...we want something that works and is simple: so something  KISS as bwctl was!
