### ISSUE TITLE
Problem with the bwctl work on FreeBSD 11

### ISSUE THREAD

**Issue by 5minmoreplease** [perfsonar/bwctl#41]
At startup bwctl can't determine the source address.
```
$ uname -a
FreeBSD node 11.0-RC1 FreeBSD 11.0-RC1 #0 r303979: Fri Aug 12 02:28:24 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
$ ./bwping -c "psum01.itep.ru:4823"
bwping: Couldn't figure out address to use to connect to psum01.itep.ru:4823
```

Trace from ./bwping -c "psum01.itep.ru:4823" [truss.txt](https://github.com/perfsonar/bwctl/files/810859/truss.txt)

Adding arguments -4 -B $local_address don't change anything.

**Comment by jonimessi** [comment]
Had the same problem with the bwctl tool. For me it helped to use the "-s"-Parameter. This parameter is also available for the bwping command.
Try: ./bwping -c psum01.itep.ru -s 10.10.10.123
In this example 10.10.10.123 is the local IP address of the interface you want to use.
At the "-c"-Parameter I am not sure if it is necessary to use the " and the port... try it out.

One other thing I had to do on machines with more then one interface is to setup a target-based Source-NAT, because I am going out on the external interface of the machine but want to use internal interface as sender... but this is a special installation, I think the first step with -s Parameter should help.
